name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
     # - 'Docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
     # - 'Docs/**'
      - '**.md'

jobs:
  linux-clang:
    runs-on: ubuntu-latest
    name: Linux Clang
    strategy:
        fail-fast: false
        matrix:
            build_type: [Distribution]

    steps:
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.24.x'
    - name: Install GTK
      run: sudo apt install build-essential libgtk-3-dev
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=clang++ -DIS_CONTAINER=True
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/ -j 2
      
  msvc_cl:
    runs-on: windows-latest
    name: Visual Studio CL
    strategy:
        fail-fast: false
        matrix:
            build_type: [Distribution]

    steps:
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.24.x'
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/ -G "Visual Studio 17 2022" -A x64 -DIS_CONTAINER=True
    - name: Build
      run: msbuild Build\Oxylus.sln /property:Configuration=${{matrix.build_type}}
