name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
     # - 'Docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
     # - 'Docs/**'
      - '**.md'

jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    name: Linux Clang
    strategy:
        fail-fast: false
        matrix:
            build_type: [Dist]

    steps:
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
         version: latest
         cache: true
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=clang++ Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/ -j 2
    - name: Run
      working-directory: ${{github.workspace}}/OxylusEditor
      run: ${{github.workspace}}/Build/OxylusEditor/Dist/OxylusEditor.exe
      
  msvc_cl:
    runs-on: windows-latest
    name: Visual Studio CL
    strategy:
        fail-fast: false
        matrix:
            build_type: [Dist]

    steps:
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
         version: latest
         cache: true
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/ -G "Visual Studio 17 2022" -A x64 Build
    - name: Build
      run: msbuild Build\Oxylus.sln /property:Configuration=${{matrix.build_type}}
    - name: Run
      working-directory: ${{github.workspace}}/OxylusEditor
      run: ${{github.workspace}}/Build/OxylusEditor/Dist/OxylusEditor.exe